set hlsearch
set textwidth=80
set incsearch
set smartcase
set modeline
set ls=2
set hidden
set noswapfile
set backspace=2

set tabstop=4
set shiftwidth=4
set softtabstop=4
set noexpandtab " use tabs not spaces
set nosmarttab " insert tabs on the start of a line according to shiftwidth, not tabstop



call plug#begin('~/.vim/plugged')
Plug 'w0rp/ale'
Plug 'kien/ctrlp.vim'
Plug 'tpope/vim-fugitive'
Plug 'elzr/vim-json'
Plug 'airblade/vim-gitgutter'
Plug 'bling/vim-airline'

call plug#end()


"kien/ctrlp.vim
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlPMixed'
let g:ctrlp_working_path_mode = 0

